# Generated by Django 4.2.5 on 2023-10-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='First_Name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_Name',
            new_name='lname',
        ),
    ]
