# Generated by Django 4.2.5 on 2023-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
