# Generated by Django 4.2.5 on 2023-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_student_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='mkdircd96@gmail.com', max_length=244, unique=True, verbose_name='email address'),
        ),
    ]
