# Generated by Django 4.2.5 on 2023-10-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_remove_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
