# Generated by Django 4.2.5 on 2023-10-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
