# Generated by Django 4.2.5 on 2023-11-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='image/'),
        ),
    ]
