# Generated by Django 4.2.5 on 2023-11-23 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default=datetime.date, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
