# Generated by Django 4.2.5 on 2023-11-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_student_comment_alter_student_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='comment',
        ),
        migrations.AddField(
            model_name='student1',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
