# Generated by Django 4.2.5 on 2023-11-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_remove_student_comment_student1_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='comments',
            field=models.TextField(max_length=500),
        ),
    ]
