# Generated by Django 4.2.5 on 2023-11-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_student1_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
