# Generated by Django 4.2.5 on 2023-11-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_alter_student1_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student1',
            name='comments',
        ),
    ]
