# Generated by Django 4.2.5 on 2023-12-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_remove_student1_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default=None, max_length=300, null=True, upload_to='uploads/'),
        ),
    ]
