# Generated by Django 4.2.5 on 2023-12-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='uploads/'),
        ),
    ]
