# Generated by Django 4.2.5 on 2023-12-14 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0024_remove_student_profile_pic_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student1',
            name='review',
        ),
        migrations.AddField(
            model_name='student1',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='student1',
            name='user',
            field=models.OneToOneField(default=-2022, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
