# Generated by Django 4.2.5 on 2023-12-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_remove_student1_review_student1_upload_student1_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
