# Generated by Django 4.2.5 on 2023-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_alter_student1_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='upload',
            field=models.FileField(blank=True, default=None, max_length=254, null=True, upload_to='uploads/'),
        ),
    ]
