# Generated by Django 4.2.5 on 2023-12-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_delete_student1_student_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
